epoch_change: |
  ğŸ†•âœ¨ğŸ”„ NEW EPOCH! âœ¨ğŸ†•

  â€¢ {{asset_name}}
  â€¢ Epoch: {{epoch_change}}

cap_change: |
  âš¡ï¸ğŸ”§âš¡ï¸ CAPACITY LIMIT CHANGED âš¡ï¸ğŸ”§âš¡ï¸

  â€¢ {{asset_name}}
  â€¢ Change: {{cap_diff}} 
  â€¢ Capacity: {{prev.lst_cap}} â†’ {{lst_cap}} ${{asset_ticker}}

tvl_change: |
  ğŸ“ˆ Capacity changed

  Asset: {{asset_name}}
  Change: {{tvl_diff}} {{asset_ticker}}
  Filled: {{lst_tvl}} / {{lst_cap}} ${{asset_ticker}}

stats: |
  ğŸ” **Stats {{asset_name}}**
  â€¢ Epoch : {{epoch}}
  â€¢ Vault capacity : {{lst_tvl}} / {{lst_cap}} ${{asset_ticker}}
  â€¢ Asset APY : {{lst_apy}}% (all time)
  â€¢ Current price     : ${{current_price}}


status: |
  ğŸ“Š **Current status â€“ {{asset_name}}**
  â€¢ Ticker          : {{asset_ticker}}
  â€¢ Epoch           : {{epoch}}
  â€¢ Vault capacity  : {{lst_tvl}} / {{lst_cap}} ${{asset_ticker}}
  â€¢ Asset APY        : {{lst_apy}}% (all time)
  â€¢ Current price     : ${{current_price}}